server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 8000;
    listen [::]:8000;

    server_name _;
    return 308 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    root /var/www/html;
    index index.html;

    server_name _;
    ssl_certificate /var/lib/exeuntu-pve/web-terminal/server.crt;
    ssl_certificate_key /var/lib/exeuntu-pve/web-terminal/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_tickets off;

    location = /xterm {
        return 308 /xterm/;
    }

    location /xterm/ {
        auth_basic "exeuntu terminal";
        auth_basic_user_file /var/lib/exeuntu-pve/web-terminal/htpasswd;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
        proxy_pass http://127.0.0.1:7681;
    }

    location / {
        sub_filter '__HOSTNAME__' $host;
        sub_filter_once off;
        try_files $uri $uri/ =404;
    }
}
